[package]
name = "dkls"
version = "0.1.0"
edition = "2024"

[dependencies]
# We don't use it directy, but we need to enable `serde` feature
generic-array = { version = "0.14", features = ["serde"] }
# `generic-ec/udigest` makes `Points<E>` implements `udigest::Digestable`
generic-ec = { version = "0.5.2", default-features = false, features = ["alloc", "serde", "udigest"] }
generic-ec-zkp = { version = "0.5.0", default-features = false, features = ["alloc"] }
rand_core = { version = "0.6", default-features = false }
round-based = { version = "0.5.0-alpha.1", default-features = false, features = ["derive"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
sha2 = { version = "0.10", default-features = false }
thiserror = { version = "2", default-features = false }
udigest = { version = "0.2", default-features = false, features = ["derive", "digest", "alloc"] }

[dev-dependencies]
# Use a concrete curve for the tests
generic-ec = { version = "0.5.2", default-features = false, features = ["curve-secp256k1"] }
rand = "0.8" # Compatible with its dependency `rand_core` https://crates.io/crates/rand/0.8.0/dependencies
rand_dev = "0.1"
round-based = { version = "0.5.0-alpha.1", features = ["derive", "sim", "sim-async", "state-machine"]  }
tokio = { version = "1.15", features = ["macros", "rt"] }
